"""add active option

Revision ID: 4304724871c2
Revises: 784ef27938d0
Create Date: 2022-08-11 10:16:04.228162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4304724871c2'
down_revision = '784ef27938d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'active')
    # ### end Alembic commands ###
