"""fix unique constraint

Revision ID: 668fb224d575
Revises: b618b17efee2
Create Date: 2022-08-16 14:39:36.959927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668fb224d575'
down_revision = 'b618b17efee2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blocks_sequence_key', 'blocks', type_='unique')
    op.create_unique_constraint(None, 'blocks', ['page_id', 'sequence'], deferrable='True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blocks', type_='unique')
    op.create_unique_constraint('blocks_sequence_key', 'blocks', ['sequence'])
    # ### end Alembic commands ###
