"""use blocks for page's content

Revision ID: 784ef27938d0
Revises: 9f963e0ff9fb
Create Date: 2022-08-08 17:12:17.651121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '784ef27938d0'
down_revision = '9f963e0ff9fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocks',
    sa.Column('id', sa.String(length=10), nullable=False),
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.PrimaryKeyConstraint('id', 'page_id'),
    sa.UniqueConstraint('sequence')
    )
    op.drop_column('pages', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('content', sa.VARCHAR(length=20000), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_table('blocks')
    # ### end Alembic commands ###
