"""add totp last counter

Revision ID: b45d2dbddaf7
Revises: c28d1b91fa56
Create Date: 2022-07-29 22:22:34.676730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b45d2dbddaf7'
down_revision = 'c28d1b91fa56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'totp_counter')
    # ### end Alembic commands ###
