"""set sequence as deferrable

Revision ID: b618b17efee2
Revises: 4304724871c2
Create Date: 2022-08-13 20:47:45.660594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b618b17efee2'
down_revision = '4304724871c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blocks_sequence_key', 'blocks', type_='unique')
    op.create_unique_constraint('blocks_sequence_key', 'blocks', ['sequence'], deferrable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('blocks_sequence_key', 'blocks', type_='unique')
    op.create_unique_constraint('blocks_sequence_key', 'blocks', ['sequence'])
    # ### end Alembic commands ###
