version: "3.6"

x-environment: &env
  API_DOMAIN_NAME: ${API_DOMAIN_NAME}
  WEB_DOMAIN_NAME: ${WEB_DOMAIN_NAME}

services:
  db:
    extends:
      file: docker-compose.yaml
      service: db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000 --proxy-headers
    environment:
      <<: *env
      DATABASE_URL: postgresql://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
      TOKEN_EXPIRE_MINUTES: ${TOKEN_EXPIRE_MINUTES}
      SECRET_KEY: ${SECRET_KEY}
      OTP_SECRET: ${OTP_SECRET}
    depends_on:
      db:
        condition: service_healthy

  caddy:
    build:
      context: ./web
      dockerfile: Dockerfile
      target: caddy
    command: caddy run
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    environment:
      <<: *env
    ports:
      - "80:80"
      - "443:443"

volumes:
  postgres_data: {}
  caddy_data: {}
  caddy_config: {}
